name: Benchmark Runner

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  run-benchmark:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        
    - name: Compile optimized
      run: g++ -std=c++17 -O3 main.cpp -o main
      
    - name: Run benchmark
      run: ./main
      
    - name: Save user info
      run: |
        user="${{ github.actor }}"
        echo "Saving result for user: $user"
        mkdir -p "results/$user"
        cp result.json "results/$user/result.json"
        
    - name: Commit and push results
      run: |
        git config user.name "github-actions"
        git config user.email "actions@users.noreply.github.com"
        git add results
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "📊 Add benchmark result for ${{ github.actor }}"
          git push
        else
          echo "No changes to commit"
        fi
