name: CI Pipeline

on: [push, pull_request]

jobs:
  build-test-and-benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential valgrind
        
    - name: Compile with debug symbols
      run: g++ -std=c++17 -g -O0 main.cpp -o main
      
    - name: Memory check with Valgrind
      run: |
        valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./main > valgrind_output.txt 2>&1 || VALGRIND_FAILED=1
        if [ -n "${VALGRIND_FAILED}" ]; then
          echo "::error::Valgrind found memory issues!"
          cat valgrind_output.txt
          
          # Comment on PR if applicable
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "VALGRIND_ERRORS=1" >> $GITHUB_ENV
          fi
          exit 1
        fi
        
    - name: Run and validate
      run: |
        ./main
        python3 result_checker.py || (echo "::error::Validation failed" && exit 1)
        
    - name: Prepare for benchmark
      if: success()
      run: |
        g++ -std=c++17 -O3 main.cpp -o main
        echo "${{ github.actor }}" > user.txt
        
    - name: Upload benchmark artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-${{ github.run_id }}
        path: |
          main
          result.json
          user.txt
          
    - name: Update leaderboard
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'leaderboard.yml',
            ref: context.ref
          });
