name: CI Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential
      
    - name: Compile and save log
      run: |
        g++ -std=c++17 -O2 main.cpp -o main > compile_output.txt 2>&1
        echo "### Компиляция завершена с кодом $?" >> compile_output.txt
        cat compile_output.txt
        # Проверяем успешность компиляции
        if [ $? -ne 0 ]; then
          echo "::error::Ошибка компиляции"
          exit 1
        fi
        
    - name: Run and save log
      run: |
        ./main > run_output.txt 2>&1
        echo "### Запуск завершен с кодом $?" >> run_output.txt
        cat run_output.txt
        
    - name: Validate results
      run: |
        python3 result_checker.py > validation_output.txt 2>&1
        cat validation_output.txt
        # Проверяем результат валидации
        if [ $? -ne 0 ]; then
          echo "::error::Ошибка валидации результатов"
          exit 1
        fi
        
    - name: Save all outputs
      uses: actions/upload-artifact@v4
      with:
        name: ci-outputs-${{ github.run_id }}
        path: |
          compile_output.txt
          run_output.txt
          validation_output.txt
          result.json
