name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential jq
        
    - name: Compile
      run: g++ -std=c++17 -O2 main.cpp -o main
    
    - name: Run test
      run: |
        ./main
        echo "Generation: $(jq '.generation_time' result.json) ms"
        echo "Sorting: $(jq '.sorting_time' result.json) ms"
        
    - name: Validate results
      run: python3 result_checker.py
