name: CI Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential
      
    - name: Compile
      run: g++ -std=c++17 -O2 main.cpp -o main
      
    - name: Run test
      run: |
        ./main
        echo "Содержимое result.json:"
        cat result.json || echo "Файл не создан"
        
    - name: Validate results
      run: python3 result_checker.py
